### ISSUE TITLE
Issue interfering with Beacon operations.

### ISSUE THREAD

**Issue by CloWnicide** [Lemon-Juiced/LemonCore#5]
While trying to activate a beacon, I keep running into an issue of not being able to put `payment` items into the beacon and while searching through the logs I found the following entry: [Worker-ResourceReload-2/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag minecraft:beacon_payment_items as it is missing following references: lemon_core:silcon (from lemon_core-1.20.1-1.0.48.jar)

Unsure if it is related to my exact problem, so posting here just in case.

**Comment by CloWnicide** [comment]
Removed Lemon-core and its dependencies and the issue has gone away. Please fix the issue with tags interfering with things that they shouldn't.

**Comment by Lemon-Juiced** [comment]
I see what the issue is, and its an oversight on my end. "lemon_core:silcon" is a typo, I can patch this in a moment

**Comment by Lemon-Juiced** [comment]
The issue should be resolved in the 1.20.1 Forge and 1.20.2 NeoForge versions of the mod now.
